name: curling_scoreboard_flutter
description: A simple app to keep setup, track, and report the scoreboard of a game of curling.
publish_to: "none"
version: 0.0.28
environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: 3.38.3
dependencies:
  # Not actually used, but needed to suppress warnings. Gets tree shaken out at build time.
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  material_segmented_control: ^5.0.1
dev_dependencies:
  build_runner: ^2.10.4
  build_version: ^2.1.2
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  translations_cleaner: ^0.0.5
  very_good_analysis: ^10.0.0
flutter:
  generate: true
  uses-material-design: true
